name: Handle new requests

on:
  workflow_dispatch:
jobs:
  handle-request:
    env:
      ENVIRONMENT: run
    #if: startsWith(github.head_ref, 'requests/') || startsWith(github.head_ref, 'request/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
