name: Handle new requests

on:
  push:
    branches:
      - "request/*"
      - "requests/*"
    paths:
      - "requests/**"
    branches-ignore:
      - "main"
      - "master"
    paths-ignore:
      - "/*"  # Exclude changes at the root level

  pull_request:
    branches:
      - "request/*"
      - "requests/*"

jobs:
  handle-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
